// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2026, 7:59:14 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Projects/nuxt-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/plugins/**/*.{js,ts,mjs}","D:/Projects/nuxt-fe/app/composables/**/*.{js,ts,mjs}","D:/Projects/nuxt-fe/app/utils/**/*.{js,ts,mjs}","D:/Projects/nuxt-fe/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/nuxt-fe/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;