// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/6/2026, 3:56:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/soetomo_5/lineproject/nuxt-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/plugins/**/*.{js,ts,mjs}","/Users/soetomo_5/lineproject/nuxt-fe/app/composables/**/*.{js,ts,mjs}","/Users/soetomo_5/lineproject/nuxt-fe/app/utils/**/*.{js,ts,mjs}","/Users/soetomo_5/lineproject/nuxt-fe/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/soetomo_5/lineproject/nuxt-fe/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;